<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset="UTF-8">
	<title>Framework Básico</title>
	<link rel="stylesheet" href="<?php echo APP_URL; ?>/views/layouts/default/css/normalize.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL; ?>/views/layouts/default/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo APP_URL; ?>/views/layouts/default/css/main.css">
	
	<script src="<?php echo APP_URL; ?>/views/layouts/template/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
        <div class="container">
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!--<p>Hello world! This is HTML5 Boilerplate.</p>-->
        
        
        <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo APP_URL?> /pages">Money Tracking</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
            <li><a href="<?php echo APP_URL?> /users">Usuarios </a></li>
            <li><a href="<?php echo APP_URL?> /types">Tipos de usuarios </a></li>
            <li><a href="<?php echo APP_URL?> /categories">Categorias </a></li>
            <li><a href="<?php echo APP_URL?> /accounts">Cuentas </a></li>
            <li><a href="<?php echo APP_URL?> /transactions">Transacciones </a></li>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Hola <?php echo $_SESSION["username"]; ?></a></li>
        <li><a href="<?php echo APP_URL."/users/logout";?>">Salir</a></li>
        
        
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>